pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

trigger: 
  - '*'

pr:
- master

name: pr$(rev:rrr)
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArgs: >
      /p:AssemblyVersion=1.0.0.0
      /p:FileVersion=1.0.$(Build.BuildId).0
      /p:InformationalVersion="$(Build.DefinitionName) $(Build.SourceBranchName) $(Build.SourceVersion)"

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Test.Unit*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish AssociateTestsToTestCases Executable'
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/AssociateTestsToTestCases/bin/$(buildConfiguration)/net8.0'
    artifactName: 'AssociateTestsToTestCases'
    publishLocation: 'Container'
